// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2,
// the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

/*
 * INCOMPLETE CODE 
 * TODO --
 *  1. return linked list from generate fibonacci to n function
 *  2. create filtured_arr function
 *  3. create array_sum function
 */
#include <stdio.h>


int str_to_int(char *s){
  int i=0;
  int num=0;
  while (s[i]!='\0') {
    int temp = s[i]-48;
    num = (num * 10) + temp;
    i++;
   } 
  return num;
}



// generate and return fibonacci series
int generate_fibonacci_to_n(int n){
  int *array = (int*)malloc(n * sizeof(int));
  int prev=0,curr=0;
  if(array == NULL){
    printf("Memory Allocation Failed\n");
    exit(1);
  }
  while (curr<n) {
    if(curr==0){

    }
  }

  return ;
}


//

int main(int argc, char *argv[])
{
  int n  = str_to_int(argv[1]);
  int *arr = generate_fibonacci_to_n(n);
  int *filtured_arr = get_xs_denominators_list(arr,2);
  int sum = array_sum(filtured_arr);
  printf("%d\n",sum);
  
  return 0 ;
}
